### ISSUE TITLE
CMake files are installed into the wrong place

### ISSUE THREAD

**Issue by ryandesign** [BIC-MNI/libminc#104]
libminc installs the files LIBMINCConfig.cmake and UseLIBMINC.cmake into the lib subdirectory of the installation prefix. That's not where CMake files go.

**Comment by thewtex** [comment]
xref https://github.com/InsightSoftwareConsortium/ITK/pull/754

**Comment by vfonov** [comment]
fixed in 44fae20d3846c9be40f38bfac73b16275f731a2e
