### ISSUE TITLE
Having `CMAKE_MINIMUM_REQUIRED(VERSION 2.8)` now causes cmake warning

### ISSUE THREAD

**Issue by seanm** [BIC-MNI/libminc#112]
Currently in https://github.com/BIC-MNI/libminc/blob/develop/CMakeLists.txt there is:

```
CMAKE_MINIMUM_REQUIRED(VERSION 2.8)
```

This seems to make current versions of cmake output:

```
CMake Deprecation Warning at Modules/ThirdParty/MINC/src/libminc/CMakeLists.txt:25 (CMAKE_MINIMUM_REQUIRED):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
```

Increasing it to 3.0 silences this warning.

Does libminc actually still need 2.8.12 support?

PS: hi @vfonov !  Hope all is well!

**Comment by vfonov** [comment]
we probably can just replace 3.0 without too much trouble... minc-toolkit requires minimum 3.6.1

**Comment by gdevenyi** [comment]
Fixed by https://github.com/BIC-MNI/libminc/commit/ea8b6c311dac8c2e46aeffbaa6a363ed07aa0c56
