### ISSUE TITLE
minc2-record-test segfaults with HDF5 1.12.0

### ISSUE THREAD

**Issue by bcdarwin** [BIC-MNI/libminc#114]
Currently causing a `libminc` build failure in the Nixpkgs/NixOS CI (`git bisect` blames https://github.com/NixOS/nixpkgs/commit/669636256265f6e47cc75126b7b003c4554d0acb):

```
Start 47: minc2-record-test
47/53 Test #47: minc2-record-test ................***Exception: SegFault  0.06 sec
```

Not yet sure if this indicates an underlying issue affecting the current MINC toolkit using 1.10.x for which the test passes or is due to an API channge.

**Comment by seanm** [comment]
This test is passing for me with libminc (latest git) with hdf (latest git).

**Comment by gdevenyi** [comment]
@bcdarwin I guess this means there was a bug in hdf5 that has been since resolved? Would be interesting to see if other sub-releases pass again

**Comment by bcdarwin** [comment]
It's passing for me as well with HDF5 1.12.1, although with segfaults or other memory corruption I never know what package to blame.
