### ISSUE TITLE
Please make a new release

### ISSUE THREAD

**Issue by shai-ikko** [BIC-MNI/libminc#118]
Hello,

Since the last release of libminc, several changes happened elsewhere, which required fixes in libminc -- and those fixes have even been made in libminc's `develop` branch, but haven't made it out to a released version.

This causes issues -- the one I [ran into](https://discourse.itk.org/t/file-written-with-libminc-not-readable-in-itk/5192) was, because the code in `master` uses obsolete HDF5 version constants, when libminc is built against a recent HDF5 it always picks the latest HDF5 format, rather than the intended v1.8 format. This, in itself, is not too terrible, but because the libminc copy in ITK does include the relevant fixes, it supports *only* the v1.8 format; resulting in broken interoperability between libminc in ITK and libminc out of ITK.

The fixes have been in libminc `develop` since August 2018...

If I can help make this release happen, please let me know.

**Comment by vfonov** [comment]
perhaps help setting up automated testing of libminc with github actions (only for master branch) ?

**Comment by shai-ikko** [comment]
I'll look into it

**Comment by vfonov** [comment]
ok, you have a new release

**Comment by gdevenyi** [comment]
I don't see a new tag?
