### ISSUE TITLE
warning: empty paragraph passed to '\param' command [-Wdocumentation]

### ISSUE THREAD

**Issue by seanm** [BIC-MNI/libminc#26]
input_nifti.h and input_mgh.h have many -Wdocumentation warnings because they have many empty \param commands.

Should they just be removed (I can do that) or can someone actually fill in docs?

(I'd like for my ITK dashboard to not have to suppress this warning flag...)

**Comment by rdvincent** [comment]
try it now...

**Comment by seanm** [comment]
thanks!
