### ISSUE TITLE
APPLY_SCALING_NORM macro evil results in invalid free()

### ISSUE THREAD

**Issue by seanm** [BIC-MNI/libminc#30]
Consider hyper.c around line 1391:
```
free(temp_buffer);
```

clang analyzer correctly reports:

```
libminc/libsrc2/hyper.c:1391:5: Argument to free() is offset by 16 bytes from the start of memory allocated by malloc()
```

The APPLY_SCALING_NORM macro increments it's 3rd parameter, and thus by the time we get to free()ing it, it's not pointing to the base address.  Evil.

**Comment by rdvincent** [comment]
@seanm Yes, that was just plain wrong. It is at least mostly fixed, I still need to write a better set of test cases for some of these things.

**Comment by seanm** [comment]
Thanks.  Though you added two new warnings:

```
/libminc/testdir/minc2-hyper-test.c:34:1: No previous prototype for function 'test1'
/libminc/testdir/minc2-hyper-test.c:443:1: No previous prototype for function 'test2'
```

Would be nice to up your warning settings maybe please?

**Comment by seanm** [comment]
I'll fix them though... have a batch to upstream anyway...

**Comment by rdvincent** [comment]
@seanm - I am using gcc 4.6.3 with -Wall, which is already insanely noisy, but doesn't complain about this.
