### ISSUE TITLE
Suspicious HDF5 version check in m2util.c

### ISSUE THREAD

**Issue by seanm** [BIC-MNI/libminc#37]
m2util.c contains

```
#if (H5_VERS_MAJOR > 1) || (H5_VERS_MINOR > 6) || (H5_VERS_RELEASE > 2)
```

Is that trying to check for HDF5 > 1.6.2, because it's not... :)

**Comment by rdvincent** [comment]
Well, it is awkward but has the intended effect - anything after 1.6.2 will invoke the true branch of the conditional. If there were a 1.5.10 out there we'd have a problem...

**Comment by seanm** [comment]
The H5_VERSION_GE macro would be perfect but was only added in 1.8.7.

Still, I could basically copy-paste it...

**Comment by rdvincent** [comment]
The existing check isn't great but it is no longer really even needed. The code should probably just be written to use the "new" signature exclusively.

**Comment by seanm** [comment]
What is the minimum HDF5 version required anyway?

**Comment by vfonov** [comment]
Frankly, HDF5 1.6.XX is not going to work anyway , see here: http://www.bic.mni.mcgill.ca/pipermail/minc-development/2013-November/001138.html

**Comment by seanm** [comment]
OK, I'll do a search and nuke any 1.6-specific crud then.

**Comment by vfonov** [comment]
You can also make it conditional with #ifdefs

**Comment by vfonov** [comment]
but minc2 file with total size of attributes larger then 64kb will be unreadable
