### ISSUE TITLE
latest changes in develop branch of libminc causes register to crash 

### ISSUE THREAD

**Issue by vfonov** [BIC-MNI/libminc#39]
Crash happens in  https://github.com/BIC-MNI/libminc/blob/develop/volume_io/Volumes/volumes.c#L201

**Comment by vfonov** [comment]
Ok, I have to update to this change: https://github.com/BIC-MNI/Register/commit/0a732b4f07ad75bb78502dbe90260d3041e4ce64

**Comment by rdvincent** [comment]
Do we need to update minc-toolkit every time a submodule changes?

**Comment by vfonov** [comment]
looks like it, otherwise incompatibilites happen

**Comment by vfonov** [comment]
the develop branch , of course
