### ISSUE TITLE
3rd party code warnings, how to manage?

### ISSUE THREAD

**Issue by seanm** [BIC-MNI/libminc#43]
znzlib.c and nifti1_io.c emit quite a few warnings, but I hesitate to fix them because they are 3rd party.  Is that code maintained by upstream developers?  Do they take patches?  Should we just use a #pragma to disable certain warnings in those files?

I'd like to do *something*, so that my dashboards can be green... :)  BTW: I've set up some nightly libminc builds here:

http://my.cdash.org/index.php?project=libminc

**Comment by rdvincent** [comment]
Sean,

We cannot count on the NIfTI project to maintain this code. While it is not a high priority for me, I'm happy to incorporate fixes as they come in. I have added a few fixes for Coverity issues that I'll check in later today.

By the way, I still cannot access the CDash page. The system still reports "You cannot access this project".

**Comment by rdvincent** [comment]
See my latest commits. These should address at least some of the warnings and Coverity issues. The code builds with zero warnings for me, but I know your compiler and settings are more aggressive.

**Comment by vfonov** [comment]
Maybe we should make release 2.3 finally?

**Comment by seanm** [comment]
Maybe first fix the failing tests on my dashboards...?  (I'm looking at why you can't view them.)

**Comment by rdvincent** [comment]
I'd be happy to help create a release soon.

**Comment by seanm** [comment]
That fixes most of the warnings, thanks.  I have a patch coming that fixes a couple more.  After that, there's only this one:

libminc/nifti/nifti1_io.c:7017:27: Variable 'read_amount' is uninitialized when used here

I think the line is copy-pasted and logging the wrong thing entirely.

**Comment by seanm** [comment]
Do you concur?  I'm not sure the best way to fix that one... depends what it actually want to log...

**Comment by rdvincent** [comment]
I checked in a fix for the bogus warning...

**Comment by seanm** [comment]
Thanks!
