### ISSUE TITLE
sign compare warning, hdf_convenience.c

### ISSUE THREAD

**Issue by seanm** [BIC-MNI/libminc#49]
Just these two left:

/libminc/libsrc/hdf_convenience.c:1850:20: Comparison of integers of different signs: 'long' and 'hsize_t' (aka 'unsigned long long')
/libminc/libsrc/hdf_convenience.c:1854:36: Comparison of integers of different signs: 'long' and 'hsize_t' (aka 'unsigned long long')

Is the left side expected to basically always be unsigned?

**Comment by rdvincent** [comment]
@seanm see latest commits
