### ISSUE TITLE
minc2-read-rgb.c: 3 * pointless allocation ?

### ISSUE THREAD

**Issue by dcb314** [BIC-MNI/libminc#65]
libminc-libminc-2-3-00/testdir/minc2-read-rgb.c:121]: (style) Variable 'start' is allocated memory that is never used.
libminc-libminc-2-3-00/testdir/minc2-read-rgb.c:122]: (style) Variable 'count' is allocated memory that is never used.
libminc-libminc-2-3-00/testdir/minc2-read-rgb.c:123]: (style) Variable 'howfar' is allocated memory that is never used.

**Comment by rdvincent** [comment]
As of now, I don't believe this test is being used, so I may just remove it from the build until is is actually useful.
