### ISSUE TITLE
ITK and libminc internal compression?

### ISSUE THREAD

**Issue by gdevenyi** [BIC-MNI/libminc#69]
I've found that using the ITK MINC tools (such as using ANTs built with MINC support) produce far larger files than using native MINC tools. Presumably this is because of compression, as if I use mincconvert to compress the files, they get very small.

Is there a way to convince the ITK tools to use MINC's internal compression?

**Comment by gdevenyi** [comment]
Just following up here, wondering if this support exists?

**Comment by vfonov** [comment]
It does: https://github.com/BIC-MNI/EZminc/blob/ITK4/tools/itk_resample.cpp#L497
also , to store floating point values into shorts or bytes with slice normalization: https://github.com/BIC-MNI/EZminc/blob/ITK4/tools/itk_resample.cpp#L505

**Comment by gdevenyi** [comment]
Thanks for the help here, I've implemented compression in ANTs image writer bits here https://github.com/stnava/ANTs/pull/305
