### ISSUE TITLE
Request resync for ITK libcminc

### ISSUE THREAD

**Issue by gdevenyi** [BIC-MNI/libminc#70]
The build error fixed by https://github.com/BIC-MNI/libminc/commit/9d9c184c184aafd954307b00feac4e261cc37d58 needs to be integrated into ITK, so perhaps a resync is in order.

That would also allow me to do a PR against ANTs to resolve https://github.com/stnava/ANTs/issues/270

**Comment by gdevenyi** [comment]
Hi,

The update to libminc in ITK on March 1st didn't pull in my CMake fixes for ``round`` due to a CMakeLists.txt conflict.
https://github.com/InsightSoftwareConsortium/ITK/commit/9fd87575bf40132c8cb7ee52aca2346fdb5f7d1a

Specifcally https://github.com/BIC-MNI/libminc/blob/develop/CMakeLists.txt#L118

**Comment by vfonov** [comment]
http://review.source.kitware.com/#/c/20826/1/CMakeLists.txt

**Comment by gdevenyi** [comment]
Oops sorry about that, seems I was browsing within a given commit instead of the HEAD!
