### ISSUE TITLE
Please support HDF5 1.10 where hid_t is 64 bits integer

### ISSUE THREAD

**Issue by pini-gh** [BIC-MNI/libminc#74]
Hi,

The subject says it all :)
There are many place into libminc source code where type <tt>int</tt> is used in place of <tt>hid_t</tt>. It badly breaks with HDF5 1.10 where [hid_t was promoted to 64 bits integer](https://www.hdfgroup.org/HDF5/doc/ADGuide/Changes.html).

Thanks in advance.

**Comment by rdvincent** [comment]
This is now fixed in develop.
