### ISSUE TITLE
Clarify licence and address common concerns

### ISSUE THREAD

**Issue by gdevenyi** [BIC-MNI/libminc#76]
People seem to think MINC is LGPL. I actually don't know.

Anyways, I don't see the LICENCE here.

If it is LGPL, it seems people think some some things about it that may not be true re: linking. We should proactively address these concerns.

**Comment by rdvincent** [comment]
@gdevenyi Please see the file COPYING. MINC is released under a minimal, MIT-like license. Most of the older tools under similar licenses. Some of the components of the overall toolkit are covered by other licenses.

**Comment by gdevenyi** [comment]
Thanks @rdvincent I missed COPYING
