### ISSUE TITLE
Microsoft now supplies ``rint``

### ISSUE THREAD

**Issue by gdevenyi** [BIC-MNI/libminc#77]
This needs some kind of version checking, newer versions of microsoft compilers supply rint.

https://github.com/BIC-MNI/libminc/blob/develop/libsrc2/minc2_private.h#L210

See https://github.com/CobraLab/atlases/issues/6

**Comment by rdvincent** [comment]
@gdevenyi Sure, I have made some effort to get the code building on Windows again, but progress has been slow.

**Comment by vfonov** [comment]
the last time I touched Windows development was a couple of years ago. 
Personally, I have no desire to do it again.

**Comment by rdvincent** [comment]
I understand...

**Comment by gdevenyi** [comment]
I know windows dev is an ugly ugly thing, but some ITK tools want a auto-building windows version, so if we want to get libminc into ITK's standard release we need to get it building on windows.

**Comment by rdvincent** [comment]
@gdevenyi No argument. It's mostly an issue of the availability of time and platforms...

**Comment by vfonov** [comment]
Well, officially we don't have any windows machines nor Visual Studio licenses in the lab, anyway.

**Comment by rdvincent** [comment]
@vfonov Exactly. I use one of my home machines to occasionally try to build for Windows. Adequate tools are available free.

**Comment by thewtex** [comment]
Addressed in #85
