### ISSUE TITLE
Documentation to miget_dimension_sampling_flag is wrong

### ISSUE THREAD

**Issue by vfonov** [BIC-MNI/libminc#78]
Documentation says:
miget_dimension_sampling_flag returns **True** if dimension is **regularly** sampled, however https://github.com/BIC-MNI/libminc/blob/develop/libsrc2/dimension.c#L1111 returns **True** if dimension is **irregularly** sampled

same goes for https://github.com/BIC-MNI/libminc/blob/develop/libsrc2/dimension.c#L1124

**Comment by rdvincent** [comment]
Fixed doc in wikibooks here:

https://en.wikibooks.org/wiki/MINC/SoftwareDevelopment/MINC2.0_Application_Programmers_Interface#miget_dimension_sampling_flag.2Fmiset_dimension_sampling_flag
