### ISSUE TITLE
memory leak/issue miget_real_value_hyperslab?

### ISSUE THREAD

**Issue by mcvaneede** [BIC-MNI/libminc#80]
Most of our code works on large numbers of files and reads in a single (or 10) slice(s) of each of the files, performs some calculation, and moves on. The assumption being that the memory usage of those programs shouldn't really exceed number_files * 1 * length_y_dim * length_z_dim * 8 bytes. Often the memory used is orders of magnitude larger. 

I've written a very simply c program that repeatedly reads the same 10x10x10 hyperslab from a fairly large file (482x956x630). The only malloc in the code is for that buffer (i.e. 8MB). However, when you run this program, its memory usage steadily increases. Does this indeed point to a memory leak related to miget_real_value_hyperslab(), or is there something wrong in this script?

```
#include <stdlib.h>
#include <minc2.h>


int main(int argc, char *argv[]) {
    int result;
    mihandle_t hvol;
    int ndims;
    midimhandle_t dimensions[5];
    misize_t sizes[5];
    misize_t count[5];
    misize_t start[3];
    double *buffer;    
    
    if( argc != 2) {
        printf("Please supply a MINC input file\n");
        return 0;
    }

    result = miopen_volume(argv[1], MI2_OPEN_READ, &hvol);
    if (result != MI_NOERROR) {
        fprintf(stderr, "\nError: opening the input file: %s\n", argv[1]);
        return -1;
    }

    // get some information about the volume
    result = miget_volume_dimension_count(hvol, MI_DIMCLASS_ANY, MI_DIMATTR_ALL, &ndims);
    result = miget_volume_dimensions(hvol, MI_DIMCLASS_ANY, MI_DIMATTR_ALL, MI_DIMORDER_FILE, ndims, dimensions);
    result = miget_dimension_sizes(dimensions, ndims, sizes);
    fprintf(stdout, "Dim sizes : %llu, %llu, %llu\n", sizes[0], sizes[1], sizes[2]);
    
    start[0] = start[1] = start[2] =0;
    count[0] = count[1] = count[2] = 10;
    buffer = (double *) malloc( 10 * 10 * 10 * sizeof(double));
    
    for(int i=0; i < 10000000; i++){

        result = miget_real_value_hyperslab(hvol, MI_TYPE_DOUBLE, start, count, buffer);
        if (result != MI_NOERROR) {
            fprintf(stderr, "\nError while getting hyperslab\n");
            return -1;
        }
        if( i % 100 == 0) {
            fprintf(stdout, ". ");
            fflush(stdout);
        }
    }

    fprintf(stdout, "\nDone.\n");
    miclose_volume(hvol);
    return result;
}
```

**Comment by rdvincent** [comment]
@mcvaneede I just pushed a fix to develop. There were two resource leaks in hyper.c that were probably affecting you. I am in the process of adapting your example to use as an automatic test in the future.

**Comment by mcvaneede** [comment]
Awesome, thanks Bert!!

**Comment by vfonov** [comment]
Probably, running tests with address sanitizer will catch errors like this without writing additional tests

**Comment by vfonov** [comment]
OK, turns out that hdf if pretty good in cleaning up after itself, asan can't detect that memory is leaked inside the loop, once MINC file is closed

**Comment by rdvincent** [comment]
@vfonov Yes, I have written a test that exercises this bug. I'll check it in later today.
