### ISSUE TITLE
VIO_PREFIX_NAMES

### ISSUE THREAD

**Issue by melrobin** [BIC-MNI/libminc#81]
Code for this version of libminc does not seem to do much with VIO_PREFIX_NAMES.  Previous versions had typedefs to not break software using the older namespace.  The line in volume_io/Include/volume_io.h:#define VIO_PREFIX_NAMES 1      /* Don't allow old-fashioned namespace pollution */
seems to want to address this, but there are no other points in the library that actually use this.  

In particular the development version of Freesurfer uses General_transform, but libminc only has VIO_General_transform.  There are a number of other datatypes that are broken by VIO_PREFIX_NAMES not working.

**Comment by vfonov** [comment]
Hello,

VIO_PREFIX_NAMES was old-style way to specify that you *WANT* VIO_<XXX> style names. Now all names are like this, that's why this macro is not used inside libminc, and is permanently set to 1. 
One would have to fix Freesurfer and any other place to use VIO_ prefix.
