### ISSUE TITLE
m4 unavailable

### ISSUE THREAD

**Issue by melrobin** [BIC-MNI/libminc#93]
The M4 files for tag release-1.5.00 are not available.  When trying to build after checking this out the message says:
[melrobin@scorpion libminc]$ ./autogen.sh
The required m4 files were not found.
You need to check these out from their repository
using

    cvs -d /software/source checkout -d m4 libraries/mni-acmacros

then the CVS command fails:
[melrobin@scorpion libminc]$ cvs -d /software/source checkout -d m4 libraries/mni-acmacros
cvs [checkout aborted]: /software/source/CVSROOT: No such file or directory

How can I check out the source to build this version?

**Comment by andrewjanke** [comment]
Hi,

have a look here:

   https://github.com/BIC-MNI/mni-acmacros

Seems that release was still using cvs before I ported everything across to
github.

ta

a

**Comment by melrobin** [comment]
OK, I cloned these to an m4 directory.  Thanks!
