### ISSUE TITLE
MINC should not pass MI2_* flags to backends 

### ISSUE THREAD

**Issue by gerddie** [BIC-MNI/libminc#94]
Specifically micreate uses a common cmode parameter that is used to pick the IO backend. However, this parameter also houses the back-end flags and is passed without changes to the selected backend. 

In the case of MI2_CREATE_V1 this is a fatal mistake, since this results in calling nccreate, and in netcdf the value of MI2_CREATE_V1 0x2000 is actually interpreted as NC_MPIPOSIX, which in the case of netcdf-4.6 results in either failure to open the file (if parallel support was not compiled in) or other unknown consequences, if parallel support was compiled in.

See also https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=888925

**Comment by vfonov** [comment]
I suppose the easiest fix would be to change the value of MI2_CREATE_V1 to 0x10000 and then mask flags passed to nccreate with 0xffff , since only lower 16 bits are used in nccreate ?

**Comment by gerddie** [comment]
Yes, that would be possible, but you should also take a look at HDF5, there you do the same. While you are at it, in the Debian bug they also write that nccreate and the related v2 API are now deprecated, and nc_create from the v3 API should be used instead.
