### ISSUE TITLE
New release? 

### ISSUE THREAD

**Issue by gerddie** [BIC-MNI/libminc#95]
Hello, 

according to [this discussion](https://discourse.itk.org/t/itk-4-13-tests-failing-and-i-cant-report-is-as-bug/687/2) ITK contributed some fixes to minc, but apparently they are not yet included in the latest released version. Could you please make a new release with these new updates?

many thanks, 
Gert

**Comment by vfonov** [comment]
OK, I made a release-2.4.03

**Comment by gerddie** [comment]
thanks
