### ISSUE TITLE
HDF5 versioning limitations in 1.10.x

### ISSUE THREAD

**Issue by gdevenyi** [BIC-MNI/libminc#99]
During my odyssey into fixing the on disk format for HDF5 1.10.x I discovered one other issue:

HDF5 1.10.0 and 1.10.1 do not have the H5F_LIBVER_V18 feature, so it is not possible via the current fix to handle them.

There are two other solutions
1) Build with --with-default-api-version=v18
or
2) #define H5_USE_18_API as documented in H5version.h

**Comment by thewtex** [comment]
:+1:  I am also running into this issue with the system HDF5 that comes with Ubuntu 18.04, which is version 1.10.0.

I suppose option number 3 is to not support HDF5 1.10.0 or 1.10.1, but that is disappointing for a long-term support Ubuntu release.

2. seems like the best option, but it would be interesting to get the input of the HDF5 folks.

CC @dzenanz
